export interface Action {
  title: string;
  desc: string;
  type: "action" | "history" | "tab" | "bookmark";
  action: string;
  emoji?: boolean;
  emojiChar?: string;
  url?: string;
  keyCheck?: boolean;
  keys?: string[];
  favIconUrl?: string;
  bookmarkId?: string;
}

const actionsList: {
  [key: string]: Action;
} = {
  mute: {
    title: "Mute tab",
    desc: "Mute the current tab",
    type: "action",
    action: "mute",
    emoji: true,
    emojiChar: "🔇",
    keyCheck: true,
    keys: ["⌥", "⇧", "M"],
  },
  unmute: {
    title: "Unmute tab",
    desc: "Unmute the current tab",
    type: "action",
    action: "unmute",
    emoji: true,
    emojiChar: "🔈",
    keyCheck: true,
    keys: ["⌥", "⇧", "M"],
  },
  pin: {
    title: "Pin tab",
    desc: "Pin the current tab",
    type: "action",
    action: "pin",
    emoji: true,
    emojiChar: "📌",
    keyCheck: true,
    keys: ["⌥", "⇧", "P"],
  },
  unpin: {
    title: "Unpin tab",
    desc: "Unpin the current tab",
    type: "action",
    action: "unpin",
    emoji: true,
    emojiChar: "📌",
    keyCheck: true,
    keys: ["⌥", "⇧", "P"],
  },
  newTab: {
    title: "New tab",
    desc: "Open a new tab",
    type: "action",
    action: "new-tab",
    emoji: true,
    emojiChar: "✨",
    keyCheck: true,
    keys: ["⌘", "T"],
  },
  bookmark: {
    title: "Bookmark",
    desc: "Create a bookmark",
    type: "action",
    action: "create-bookmark",
    emoji: true,
    emojiChar: "📕",
    keyCheck: true,
    keys: ["⌘", "D"],
  },
  fullscreen: {
    title: "Fullscreen",
    desc: "Make the page fullscreen",
    type: "action",
    action: "fullscreen",
    emoji: true,
    emojiChar: "🖥",
    keyCheck: true,
    keys: ["⌘", "Ctrl", "F"],
  },
  reload: {
    title: "Reload",
    desc: "Reload the page",
    type: "action",
    action: "reload",
    emoji: true,
    emojiChar: "♻️",
    keyCheck: true,
    keys: ["⌘", "⇧", "R"],
  },
  help: {
    title: "Help",
    desc: "Get help with Omni on GitHub",
    type: "action",
    action: "url",
    url: "https://github.com/alyssaxuu/omni",
    emoji: true,
    emojiChar: "🤔",
  },
  email: {
    title: "Compose email",
    desc: "Compose a new email",
    type: "action",
    action: "email",
    emoji: true,
    emojiChar: "✉️",
    keyCheck: true,
    keys: ["⌥", "⇧", "C"],
  },
  notion: {
    title: "New Notion page",
    desc: "Create a new Notion page",
    type: "action",
    action: "url",
    url: "https://notion.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-notion.png"),
  },
  sheets: {
    title: "New Sheets spreadsheet",
    desc: "Create a new Google Sheets spreadsheet",
    type: "action",
    action: "url",
    url: "https://sheets.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-sheets.png"),
  },
  docs: {
    title: "New Docs document",
    desc: "Create a new Google Docs document",
    type: "action",
    action: "url",
    url: "https://docs.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-docs.png"),
  },
  slides: {
    title: "New Slides presentation",
    desc: "Create a new Google Slides presentation",
    type: "action",
    action: "url",
    url: "https://slides.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-slides.png"),
  },
  forms: {
    title: "New form",
    desc: "Create a new Google Forms form",
    type: "action",
    action: "url",
    url: "https://forms.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-forms.png"),
  },
  medium: {
    title: "New Medium story",
    desc: "Create a new Medium story",
    type: "action",
    action: "url",
    url: "https://story.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-medium.png"),
  },
  githubRepo: {
    title: "New GitHub repository",
    desc: "Create a new GitHub repository",
    type: "action",
    action: "url",
    url: "https://github.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-github.png"),
  },
  githubGist: {
    title: "New GitHub gist",
    desc: "Create a new GitHub gist",
    type: "action",
    action: "url",
    url: "https://gist.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-github.png"),
  },
  codePen: {
    title: "New CodePen pen",
    desc: "Create a new CodePen pen",
    type: "action",
    action: "url",
    url: "https://pen.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-codepen.png"),
  },
  excel: {
    title: "New Excel spreadsheet",
    desc: "Create a new Excel spreadsheet",
    type: "action",
    action: "url",
    url: "https://excel.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-excel.png"),
  },
  powerPoint: {
    title: "New PowerPoint presentation",
    desc: "Create a new PowerPoint presentation",
    type: "action",
    url: "https://powerpoint.new",
    action: "url",
    favIconUrl: chrome.runtime.getURL("icons/logo-powerpoint.png"),
  },
  word: {
    title: "New Word document",
    desc: "Create a new Word document",
    type: "action",
    action: "url",
    url: "https://word.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-word.png"),
  },
  whiteboard: {
    title: "Create a whiteboard",
    desc: "Create a collaborative whiteboard",
    type: "action",
    action: "url",
    url: "https://whiteboard.new",
    emoji: true,
    emojiChar: "🧑‍🏫",
  },
  video: {
    title: "Record a video",
    desc: "Record and edit a video",
    type: "action",
    action: "url",
    url: "https://recording.new",
    emoji: true,
    emojiChar: "📹",
  },
  figma: {
    title: "Create a Figma file",
    desc: "Create a new Figma file",
    type: "action",
    action: "url",
    url: "https://figma.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-figma.png"),
  },
  figJam: {
    title: "Create a FigJam file",
    desc: "Create a new FigJam file",
    type: "action",
    action: "url",
    url: "https://figjam.new",
    emoji: true,
    emojiChar: "🖌",
  },
  productHunt: {
    title: "Hunt a product",
    desc: "Submit a product to Product Hunt",
    type: "action",
    action: "url",
    url: "https://www.producthunt.com/posts/new",
    favIconUrl: chrome.runtime.getURL("icons/logo-producthunt.png"),
  },
  tweet: {
    title: "Make a tweet",
    desc: "Make a tweet on Twitter",
    type: "action",
    action: "url",
    url: "https://twitter.com/intent/tweet",
    favIconUrl: chrome.runtime.getURL("icons/logo-twitter.png"),
  },
  spotify: {
    title: "Create a playlist",
    desc: "Create a Spotify playlist",
    type: "action",
    action: "url",
    url: "https://playlist.new",

    favIconUrl: chrome.runtime.getURL("icons/logo-spotify.png"),
  },
  canva: {
    title: "Create a Canva design",
    desc: "Create a new design with Canva",
    type: "action",
    action: "url",
    url: "https://design.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-canva.png"),
  },
  episode: {
    title: "Create a new podcast episode",
    desc: "Create a new podcast episode with Anchor",
    type: "action",
    action: "url",
    url: "https://episode.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-anchor.png"),
  },
  photoshop: {
    title: "Edit an image",
    desc: "Edit an image with Adobe Photoshop",
    type: "action",
    action: "url",
    url: "https://photo.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-photoshop.png"),
  },
  convertPDF: {
    title: "Convert to PDF",
    desc: "Convert a file to PDF",
    type: "action",
    action: "url",
    url: "https://pdf.new",
    emoji: true,
    emojiChar: "📄",
  },
  scanQR: {
    title: "Scan a QR code",
    desc: "Scan a QR code with your camera",
    type: "action",
    action: "url",
    url: "https://scan.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-qr.png"),
  },
  asana: {
    title: "Add a task to Asana",
    desc: "Create a new task in Asana",
    type: "action",
    action: "url",
    url: "https://task.new",

    favIconUrl: chrome.runtime.getURL("icons/logo-asana.png"),
  },
  linear: {
    title: "Add an issue to Linear",
    desc: "Create a new issue in Linear",
    type: "action",
    action: "url",
    url: "https://linear.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-linear.png"),
  },
  todo: {
    title: "Add a task to WIP",
    desc: "Create a new task in WIP",
    type: "action",
    action: "url",
    url: "https://todo.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-wip.png"),
  },
  calendar: {
    title: "Create an event",
    desc: "Add an event to Google Calendar",
    type: "action",
    action: "url",
    url: "https://cal.new",

    favIconUrl: chrome.runtime.getURL("icons/logo-calendar.png"),
  },
  keep: {
    title: "Add a note",
    desc: "Add a note to Google Keep",
    type: "action",
    action: "url",
    url: "https://note.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-keep.png"),
  },
  meet: {
    title: "New meeting",
    desc: "Start a Google Meet meeting",
    type: "action",
    action: "url",
    url: "https://meet.new",
    favIconUrl: chrome.runtime.getURL("icons/logo-meet.png"),
  },
  history: {
    title: "Browsing history",
    desc: "Browse through your browsing history",
    type: "action",
    action: "history",
    emoji: true,
    emojiChar: "🗂",
    keyCheck: true,
    keys: ["⌘", "Y"],
  },
  incognito: {
    title: "Incognito mode",
    desc: "Open an incognito window",
    type: "action",
    action: "incognito",
    emoji: true,
    emojiChar: "🕵️",
    keyCheck: true,
    keys: ["⌘", "⇧", "N"],
  },
  downloads: {
    title: "Downloads",
    desc: "Browse through your downloads",
    type: "action",
    action: "downloads",
    emoji: true,
    emojiChar: "📦",
    keyCheck: true,
    keys: ["⌘", "⇧", "J"],
  },
  extensions: {
    title: "Extensions",
    desc: "Manage your Chrome Extensions",
    type: "action",
    action: "extensions",
    emoji: true,
    emojiChar: "🧩",

    keys: ["⌘", "D"],
  },
  settings: {
    title: "Chrome settings",
    desc: "Open the Chrome settings",
    type: "action",
    action: "settings",
    emoji: true,
    emojiChar: "⚙️",
    keyCheck: true,
    keys: ["⌘", ","],
  },
  scrollBottom: {
    title: "Scroll to bottom",
    desc: "Scroll to the bottom of the page",
    type: "action",
    action: "scroll-bottom",
    emoji: true,
    emojiChar: "👇",
    keyCheck: true,
    keys: ["⌘", "↓"],
  },
  scrollTop: {
    title: "Scroll to top",
    desc: "Scroll to the top of the page",
    type: "action",
    action: "scroll-top",
    emoji: true,
    emojiChar: "👆",
    keyCheck: true,
    keys: ["⌘", "↑"],
  },
  goBack: {
    title: "Go back",
    desc: "Go back in history for the current tab",
    type: "action",
    action: "go-back",
    emoji: true,
    emojiChar: "👈",
    keyCheck: true,
    keys: ["⌘", "←"],
  },
  goForward: {
    title: "Go forward",
    desc: "Go forward in history for the current tab",
    type: "action",
    action: "go-forward",
    emoji: true,
    emojiChar: "👉",
    keyCheck: true,
    keys: ["⌘", "→"],
  },
  duplicateTab: {
    title: "Duplicate tab",
    desc: "Make a copy of the current tab",
    type: "action",
    action: "duplicate-tab",
    emoji: true,
    emojiChar: "📋",
    keyCheck: true,
    keys: ["⌥", "⇧", "D"],
  },
  closeTab: {
    title: "Close tab",
    desc: "Close the current tab",
    type: "action",
    action: "close-tab",
    emoji: true,
    emojiChar: "🗑",
    keyCheck: true,
    keys: ["⌘", "W"],
  },
  closeWindow: {
    title: "Close window",
    desc: "Close the current window",
    type: "action",
    action: "close-window",
    emoji: true,
    emojiChar: "💥",
    keyCheck: true,
    keys: ["⌘", "⇧", "W"],
  },
  manageData: {
    title: "Manage browsing data",
    desc: "Manage your browsing data",
    type: "action",
    action: "manage-data",
    emoji: true,
    emojiChar: "🔬",
    keyCheck: true,
    keys: ["⌘", "⇧", "Delete"],
  },
  clearData: {
    title: "Clear all browsing data",
    desc: "Clear all of your browsing data",
    type: "action",
    action: "remove-all",
    emoji: true,
    emojiChar: "🧹",
    keys: ["⌘", "D"],
  },
  clearHistory: {
    title: "Clear browsing history",
    desc: "Clear all of your browsing history",
    type: "action",
    action: "remove-history",
    emoji: true,
    emojiChar: "🗂",
    keys: ["⌘", "D"],
  },
  clearCookies: {
    title: "Clear cookies",
    desc: "Clear all cookies",
    type: "action",
    action: "remove-cookies",
    emoji: true,
    emojiChar: "🍪",
    keys: ["⌘", "D"],
  },
  clearCache: {
    title: "Clear cache",
    desc: "Clear the cache",
    type: "action",
    action: "remove-cache",
    emoji: true,
    emojiChar: "🗄",
    keys: ["⌘", "D"],
  },
  clearLocalStorage: {
    title: "Clear local storage",
    desc: "Clear the local storage",
    type: "action",
    action: "remove-local-storage",
    emoji: true,
    emojiChar: "📦",
    keys: ["⌘", "D"],
  },
  clearPasswords: {
    title: "Clear passwords",
    desc: "Clear all saved passwords",
    type: "action",
    action: "remove-passwords",
    emoji: true,
    emojiChar: "🔑",
    keys: ["⌘", "D"],
  },
};

export default actionsList;
