import type { Action } from "../types";

import shortcuts from "./shortcuts";
import {
  Mute,
  Speaker2,
  Pin,
  PinOff,
  Sparkle,
  BookmarkAdd,
  FullScreenMaximize,
  ArrowClockwise,
  PersonQuestionMark,
  MailAdd,
  FolderBriefcase,
  Incognito,
  DrawerArrowDownload,
  PuzzlePiece,
  Settings,
  ArrowDown,
  ArrowUp,
  ArrowStepBack,
  ArrowForward,
  PanelSeparateWindow,
  TrayItemRemove,
  Key,
  Delete,
  EyeTracking,
  Filter,
  Fingerprint,
  Cookies,
  Storage,
  Toolbox,
  Print,
} from "../icons/fluidui";

const actions: Action[] = [
  {
    title: "Mute tab",
    description: "Mute the current tab",
    type: "action",
    action: "mute",
    icon: Mute,
    showKeys: true,
    keys: ["⌥", "⇧", "M"],
  },
  {
    title: "Unmute tab",
    description: "Unmute the current tab",
    type: "action",
    action: "unmute",
    icon: Speaker2,
    showKeys: true,
    keys: ["⌥", "⇧", "M"],
  },
  {
    title: "Pin tab",
    description: "Pin the current tab",
    type: "action",
    action: "pin",
    icon: Pin,
    showKeys: true,
    keys: ["⌥", "⇧", "P"],
  },
  {
    title: "Unpin tab",
    description: "Unpin the current tab",
    type: "action",
    action: "unpin",
    icon: PinOff,
    showKeys: true,
    keys: ["⌥", "⇧", "P"],
  },
  {
    title: "New tab",
    description: "Open a new tab",
    type: "action",
    action: "new-tab",
    icon: Sparkle,
    showKeys: true,
    keys: ["⌘", "T"],
  },
  {
    title: "Bookmark",
    description: "Create a bookmark",
    type: "action",
    action: "create-bookmark",
    icon: BookmarkAdd,
    showKeys: true,
    keys: ["⌘", "D"],
  },
  {
    title: "Fullscreen",
    description: "Make the page fullscreen",
    type: "action",
    action: "fullscreen",
    icon: FullScreenMaximize,
    showKeys: true,
    keys: ["⌘", "Ctrl", "F"],
  },
  {
    title: "Reload",
    description: "Reload the page",
    type: "action",
    action: "reload",
    icon: ArrowClockwise,
    showKeys: true,
    keys: ["⌘", "⇧", "R"],
  },
  {
    title: "Help",
    description: "Get help with Sugu on GitHub",
    type: "action",
    action: "url",
    url: "https://github.com/yoroshikun/sugu",
    icon: PersonQuestionMark,
  },
  {
    title: "Compose email",
    description: "Compose a new email",
    type: "action",
    action: "email",
    icon: MailAdd,
    showKeys: true,
    keys: ["⌥", "⇧", "C"],
  },
  {
    title: "Print page",
    description: "Print the current page",
    type: "action",
    action: "print",
    icon: Print,
    showKeys: true,
    keys: ["⌘", "P"],
  },
  ...shortcuts,
  {
    title: "Browsing history",
    description: "Browse through your browsing history",
    type: "action",
    action: "history",
    icon: FolderBriefcase,
    showKeys: true,
    keys: ["⌘", "Y"],
  },
  {
    title: "Incognito mode",
    description: "Open an incognito window",
    type: "action",
    action: "incognito",
    icon: Incognito,
    showKeys: true,
    keys: ["⌘", "⇧", "N"],
  },
  {
    title: "Downloads",
    description: "Browse through your downloads",
    type: "action",
    action: "downloads",
    icon: DrawerArrowDownload,
    showKeys: true,
    keys: ["⌘", "⇧", "J"],
  },
  {
    title: "Extensions",
    description: "Manage your Chrome Extensions",
    type: "action",
    action: "extensions",
    icon: PuzzlePiece,
    keys: ["⌘", "D"],
  },
  {
    title: "Chrome settings",
    description: "Open the Chrome settings",
    type: "action",
    action: "settings",
    icon: Settings,
    showKeys: true,
    keys: ["⌘", ","],
  },
  {
    title: "Scroll to bottom",
    description: "Scroll to the bottom of the page",
    type: "action",
    action: "scroll-bottom",
    icon: ArrowDown,
    showKeys: true,
    keys: ["⌘", "↓"],
  },
  {
    title: "Scroll to top",
    description: "Scroll to the top of the page",
    type: "action",
    action: "scroll-top",
    icon: ArrowUp,
    showKeys: true,
    keys: ["⌘", "↑"],
  },
  {
    title: "Go back",
    description: "Go back in history for the current tab",
    type: "action",
    action: "go-back",
    icon: ArrowStepBack,
    showKeys: true,
    keys: ["⌘", "←"],
  },
  {
    title: "Go forward",
    description: "Go forward in history for the current tab",
    type: "action",
    action: "go-forward",
    icon: ArrowForward,
    showKeys: true,
    keys: ["⌘", "→"],
  },
  {
    title: "Duplicate tab",
    description: "Make a copy of the current tab",
    type: "action",
    action: "duplicate-tab",
    icon: PanelSeparateWindow,
    showKeys: true,
    keys: ["⌥", "⇧", "D"],
  },
  {
    title: "Close tab",
    description: "Close the current tab",
    type: "action",
    action: "close-current-tab",
    icon: TrayItemRemove,
    showKeys: true,
    keys: ["⌘", "W"],
  },
  {
    title: "Close window",
    description: "Close the current window",
    type: "action",
    action: "close-window",
    icon: Delete,
    showKeys: true,
    keys: ["⌘", "⇧", "W"],
  },
  {
    title: "Manage browsing data",
    description: "Manage your browsing data",
    type: "action",
    action: "manage-data",
    icon: Filter,
    showKeys: true,
    keys: ["⌘", "⇧", "Delete"],
  },
  {
    title: "Clear all browsing data",
    description: "Clear all of your browsing data",
    type: "action",
    action: "remove-all",
    icon: EyeTracking,
    keys: ["⌘", "D"],
  },
  {
    title: "Clear browsing history",
    description: "Clear all of your browsing history",
    type: "action",
    action: "remove-history",
    icon: Fingerprint,
    keys: ["⌘", "D"],
  },
  {
    title: "Clear cookies",
    description: "Clear all cookies",
    type: "action",
    action: "remove-cookies",
    icon: Cookies,
    keys: ["⌘", "D"],
  },
  {
    title: "Clear cache",
    description: "Clear the cache",
    type: "action",
    action: "remove-cache",
    icon: Toolbox,
    keys: ["⌘", "D"],
  },
  {
    title: "Clear local storage",
    description: "Clear the local storage",
    type: "action",
    action: "remove-local-storage",
    icon: Storage,
    keys: ["⌘", "D"],
  },
  {
    title: "Clear passwords",
    description: "Clear all saved passwords",
    type: "action",
    action: "remove-passwords",
    icon: Key,
    keys: ["⌘", "D"],
  },
];

export default actions;
