import type { Action } from "../types";

import browser from 'webextension-polyfill';
import { Board, VideoAdd, CalligraphyPen, DocumentPDF } from "../icons/fluidui";

const shortcuts: Action[] = [
  {
    title: "New Notion page",
    description: "Create a new Notion page",
    type: "action",
    action: "url",
    url: "https://notion.new",
    favIconUrl: browser.runtime.getURL("icons/logo-notion.png"),
  },
  {
    title: "New Sheets spreadsheet",
    description: "Create a new Google Sheets spreadsheet",
    type: "action",
    action: "url",
    url: "https://sheets.new",
    favIconUrl: browser.runtime.getURL("icons/logo-sheets.png"),
  },
  {
    title: "New Docs document",
    description: "Create a new Google Docs document",
    type: "action",
    action: "url",
    url: "https://docs.new",
    favIconUrl: browser.runtime.getURL("icons/logo-docs.png"),
  },
  {
    title: "New Slides presentation",
    description: "Create a new Google Slides presentation",
    type: "action",
    action: "url",
    url: "https://slides.new",
    favIconUrl: browser.runtime.getURL("icons/logo-slides.png"),
  },
  {
    title: "New form",
    description: "Create a new Google Forms form",
    type: "action",
    action: "url",
    url: "https://forms.new",
    favIconUrl: browser.runtime.getURL("icons/logo-forms.png"),
  },
  {
    title: "New Medium story",
    description: "Create a new Medium story",
    type: "action",
    action: "url",
    url: "https://story.new",
    favIconUrl: browser.runtime.getURL("icons/logo-medium.png"),
  },
  {
    title: "New GitHub repository",
    description: "Create a new GitHub repository",
    type: "action",
    action: "url",
    url: "https://github.new",
    favIconUrl: browser.runtime.getURL("icons/logo-github.png"),
  },
  {
    title: "New GitHub gist",
    description: "Create a new GitHub gist",
    type: "action",
    action: "url",
    url: "https://gist.new",
    favIconUrl: browser.runtime.getURL("icons/logo-github.png"),
  },
  {
    title: "New CodePen pen",
    description: "Create a new CodePen pen",
    type: "action",
    action: "url",
    url: "https://pen.new",
    favIconUrl: browser.runtime.getURL("icons/logo-codepen.png"),
  },
  {
    title: "New Excel spreadsheet",
    description: "Create a new Excel spreadsheet",
    type: "action",
    action: "url",
    url: "https://excel.new",
    favIconUrl: browser.runtime.getURL("icons/logo-excel.png"),
  },
  {
    title: "New PowerPoint presentation",
    description: "Create a new PowerPoint presentation",
    type: "action",
    url: "https://powerpoint.new",
    action: "url",
    favIconUrl: browser.runtime.getURL("icons/logo-powerpoint.png"),
  },
  {
    title: "New Word document",
    description: "Create a new Word document",
    type: "action",
    action: "url",
    url: "https://word.new",
    favIconUrl: browser.runtime.getURL("icons/logo-word.png"),
  },
  {
    title: "Create a whiteboard",
    description: "Create a collaborative whiteboard",
    type: "action",
    action: "url",
    url: "https://whiteboard.new",
    icon: Board,
  },
  {
    title: "Record a video",
    description: "Record and edit a video",
    type: "action",
    action: "url",
    url: "https://recording.new",
    icon: VideoAdd,
  },
  {
    title: "Create a Figma file",
    description: "Create a new Figma file",
    type: "action",
    action: "url",
    url: "https://figma.new",
    favIconUrl: browser.runtime.getURL("icons/logo-figma.png"),
  },
  {
    title: "Create a FigJam file",
    description: "Create a new FigJam file",
    type: "action",
    action: "url",
    url: "https://figjam.new",
    icon: CalligraphyPen,
  },
  {
    title: "Hunt a product",
    description: "Submit a product to Product Hunt",
    type: "action",
    action: "url",
    url: "https://www.producthunt.com/posts/new",
    favIconUrl: browser.runtime.getURL("icons/logo-producthunt.png"),
  },
  {
    title: "Make a tweet",
    description: "Make a tweet on Twitter",
    type: "action",
    action: "url",
    url: "https://twitter.com/intent/tweet",
    favIconUrl: browser.runtime.getURL("icons/logo-twitter.png"),
  },
  {
    title: "Create a playlist",
    description: "Create a Spotify playlist",
    type: "action",
    action: "url",
    url: "https://playlist.new",

    favIconUrl: browser.runtime.getURL("icons/logo-spotify.png"),
  },
  {
    title: "Create a Canva design",
    description: "Create a new design with Canva",
    type: "action",
    action: "url",
    url: "https://design.new",
    favIconUrl: browser.runtime.getURL("icons/logo-canva.png"),
  },
  {
    title: "Create a new podcast episode",
    description: "Create a new podcast episode with Anchor",
    type: "action",
    action: "url",
    url: "https://episode.new",
    favIconUrl: browser.runtime.getURL("icons/logo-anchor.png"),
  },
  {
    title: "Edit an image",
    description: "Edit an image with Adobe Photoshop",
    type: "action",
    action: "url",
    url: "https://photo.new",
    favIconUrl: browser.runtime.getURL("icons/logo-photoshop.png"),
  },
  {
    title: "Convert to PDF",
    description: "Convert a file to PDF",
    type: "action",
    action: "url",
    url: "https://pdf.new",
    icon: DocumentPDF,
  },
  {
    title: "Scan a QR code",
    description: "Scan a QR code with your camera",
    type: "action",
    action: "url",
    url: "https://scan.new",
    favIconUrl: browser.runtime.getURL("icons/logo-qr.png"),
  },
  {
    title: "Add a task to Asana",
    description: "Create a new task in Asana",
    type: "action",
    action: "url",
    url: "https://task.new",

    favIconUrl: browser.runtime.getURL("icons/logo-asana.png"),
  },
  {
    title: "Add an issue to Linear",
    description: "Create a new issue in Linear",
    type: "action",
    action: "url",
    url: "https://linear.new",
    favIconUrl: browser.runtime.getURL("icons/logo-linear.png"),
  },
  {
    title: "Add a task to WIP",
    description: "Create a new task in WIP",
    type: "action",
    action: "url",
    url: "https://todo.new",
    favIconUrl: browser.runtime.getURL("icons/logo-wip.png"),
  },
  {
    title: "Create an event",
    description: "Add an event to Google Calendar",
    type: "action",
    action: "url",
    url: "https://cal.new",
    favIconUrl: browser.runtime.getURL("icons/logo-calendar.png"),
  },
  {
    title: "Add a note",
    description: "Add a note to Google Keep",
    type: "action",
    action: "url",
    url: "https://note.new",
    favIconUrl: browser.runtime.getURL("icons/logo-keep.png"),
  },
  {
    title: "New meeting",
    description: "Start a Google Meet meeting",
    type: "action",
    action: "url",
    url: "https://meet.new",
    favIconUrl: browser.runtime.getURL("icons/logo-meet.png"),
  },
];

export default shortcuts;
